// src/utils/tagRoutes.js (you can place inside utils or common folder)

export const tagRoutes = {
  webdev: "#",
  react: "#",
  ai: "#",
  cloud: "#",
  javascript: "#",
  aiintegration: "#",
  frontend: "#",
  aws: "#",
  azure: "#",
  devops: "#",
  "no-code":"#",
  "low-code":"#",
  business: "#",
  security: "#",
  kubernetes: "#",
  sre: "#",
  containers: "#",
  typescript: "#",
  programming: "#",
  "technical-seo": "#",
  audit: "#",
  performance: "#",
  api: "#",
  owasp: "#",
  development: "#",
  cicd: "#",
  gitops: "#",
  automation: "#", 
  innovation: "#",
  encryption: "#",
  zerotrust: "#",
  seo: "#",
  google: "#",
  marketing: "#",
  frameworks: "#",  
};
